name: Create Release

on:
  pull_request:
    types: [ closed ]

jobs:
  Release:
    if: ${{ github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'Release') }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Get new version name
        run: echo version=$(echo ${{ github.event.pull_request.title }} | sed 's/.*to //') >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Create release
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # v2.2.1
        with:
          name: ${{ env.version }}
          tag_name: ${{ env.version }}
          body: |
            ## What's Changed
            Details of the features included in this release are summarized in #${{ github.event.pull_request.number }}
