name: CI Lint

on:
  pull_request_target:
    types: [ opened, reopened, synchronize, ready_for_review, converted_to_draft ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  detekt:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      pull-requests: write
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: "refs/pull/${{ github.event.pull_request.number }}/merge"

      - name: Validate Gradle Wrapper
        uses: gradle/actions/setup-gradle@94baf225fe0a508e581a564467443d0e2379123b # v4.3.0

      - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/configuration-cache
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}

      - name: Setup JDK 17
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.7.0
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup ReviewDog
        uses: reviewdog/action-setup@e04ffabe3898a0af8d0fb1af00c188831c4b5893 # v1.3.2
        with:
          reviewdog_version: latest

      - name: Run detekt and merge reports
        id: detekt
        continue-on-error: true
        run: ./gradlew detekt reportMerge --continue

      - name: Run report with ReviewDog
        if: steps.detekt.outcome == 'failure'
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: cat ./build/reports/detekt/merge.xml |
          reviewdog -f=checkstyle -name="detekt" -reporter="github-pr-review"

      - if: steps.detekt.outcome == 'failure'
        run: exit 1
