name: CI Lint

on:
  pull_request_target:
    types: [ opened, reopened, synchronize, ready_for_review, converted_to_draft ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  detekt:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      pull-requests: write
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: "refs/pull/${{ github.event.pull_request.number }}/merge"
          token: ${{ secrets.ACTIONS_PAT }}

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.konan
          key: ${{ runner.os }}-${{ hashFiles('**/.lock') }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup ReviewDog
        uses: reviewdog/action-setup@v1.3.0
        with:
          reviewdog_version: latest

      - name: Run detekt and merge reports
        id: detekt
        continue-on-error: true
        run: ./gradlew detekt reportMerge --continue

      - name: Run report with ReviewDog
        if: steps.detekt.outcome == 'failure'
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: cat ./build/reports/detekt/merge.xml |
          reviewdog -f=checkstyle -name="detekt" -reporter="github-pr-review"

      - if: steps.detekt.outcome == 'failure'
        run: exit 1
